### ISSUE TITLE
Sandboxed-module error after upgrading node module from 6.x.x to 10.x.x

### ISSUE THREAD

**Issue by Ashish131989** [felixge/node-sandboxed-module#68]
Getting TypeError: callSite.getFileName is not a function error after upgrading node version from 6.14.3 to 10.x.x.

 

I did check this with express community ( https://github.com/expressjs/express/issues/3919 ) but it seems to be a bug in the https://www.npmjs.com/package/sandboxed-module.

Could you provide the solution to fix this.

var file = callSite.getFileName() || '<anonymous>'

                      ^

TypeError: callSite.getFileName is not a function

    at callSiteLocation (C:\MMS_Github\MMS Upgrade 10\ManageMyStaff\node_modules\body-parser\node_modules\depd\index.js:252:23)

    at depd (C:\MMS_Github\MMS Upgrade 10\ManageMyStaff\node_modules\body-parser\node_modules\depd\index.js:111:14)

    at Object.<anonymous> (C:\MMS_Github\MMS Upgrade 10\ManageMyStaff\node_modules\body-parser\index.js:14:32)

    at SandboxedModule._compile (C:\MMS_Github\MMS Upgrade 10\ManageMyStaff\node_modules\sandboxed-module\lib\sandboxed_module.js:251:19)

    at createInnerSandboxedModule (C:\MMS_Github\MMS Upgrade 10\ManageMyStaff\node_modules\sandboxed-module\lib\sandboxed_module.js:183:23)

    at SandboxedModule.RecursiveRequireProxy (C:\MMS_Github\MMS Upgrade 10\ManageMyStaff\node_modules\sandboxed-module\lib\sandboxed_module.js:214:27)

    at Object.<anonymous> (C:\MMS_Github\MMS Upgrade 10\ManageMyStaff\node_modules\express\lib\express.js:15:18)

    at SandboxedModule._compile (C:\MMS_Github\MMS Upgrade 10\ManageMyStaff\node_modules\sandboxed-module\lib\sandboxed_module.js:251:19)

    at createInnerSandboxedModule (C:\MMS_Github\MMS Upgrade 10\ManageMyStaff\node_modules\sandboxed-module\lib\sandboxed_module.js:183:23)

    at SandboxedModule.RecursiveRequireProxy (C:\MMS_Github\MMS Upgrade 10\ManageMyStaff\node_modules\sandboxed-module\lib\sandboxed_module.js:214:27)

npm ERR! Test failed.  See above for more details.

 

 

Sharing the sample application with you on below path.

https://github.com/Ashish131989/depd-module-Issues

**Comment by Ashish131989** [comment]
Team- Did you get chance to look into it?

**Comment by Ashish131989** [comment]
@felixge @domenic Could you please look into it?It is blocking our development

**Comment by dberardo-com** [comment]
i faced this issue in docker containers using node:10.14.1-alpine 

changing to node:14-alpine fixes the issue, but node:12-alpine was not working either
